import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./Navbar";
import Footer from "./Footer";
import { CategoryProvider } from '../app/CategorieContext/CategoryContext';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    // we need to wrap our application with the context Provider so it can be accessible in any compnent without passing props
    <html lang="en">
      <body className={inter.className}>
        <CategoryProvider >
        <Navbar/>
        {children}
        <Footer/>
        </CategoryProvider >
        </body>
    </html>
  );
}
